#!/bin/bash 

TMPFILE="/tmp/.iirazzy.lock"
MYPATH="$(dirname "$(readlink -f "$0")" )"
cd "$MYPATH"
which ii &>/dev/null || { echo "ii not installed..halting" && exit 1; }
source config.d/global.bash

monitor() {
    tailf -n 1 "$IRCDIR/$NETWORK/$channel/out" | \
        while read -r date time nick msg; do
            # if msg is by the system ignore it
            [[ "$nick" == '-!-' ]] && continue
            # strip < and >. if msg is by ourself ignore it
            nick="${nick:1:-1}"
            [[ "$nick" == "$NICKNAME" ]] && continue

            # if msg contains a url, transform to url command
            [[ "$msg" =~ https?:// ]] && \
                exec ./iicmd "$nick" "url ${msg#* }" "$IRCDIR" "$NETWORK" "$channel" "$NICKNAME" | fold -w 255 &
            # if msg is a command, invoke iicmd
            [[ "$msg" =~ ^! ]] && \
                exec ./iicmd "$nick" "${msg#\!}" "$IRCDIR" "$NETWORK" "$channel" "$NICKNAME" | fold -w 255 &
            # filter thru pipes 
            pipes=(pipes/$NETWORK/$channel/*)
            for pipe in ${pipes[@]}; do 
              { exec $pipe "$nick" "${msg#\!}" "$IRCDIR" "$NETWORK" "$channel" "$NICKNAME" | fold -w 255; } &
            done
        done > "$IRCDIR/$NETWORK/$channel/in"
}

start(){
  [[ -f $TMPFILE ]] && echo "ii(razzy) is running, run './iirazzy stop' or remove $TMPFILE manually" && exit 1
  echo "starting iirazzy"; :>$TMPFILE;  startnetworks
  echo "$! " >> $TMPFILE
}

status(){
  [[ ! -f $TMPFILE ]] && echo "ii(razzy) is not running, run './iirazzy start' first" && exit 1
  find irc
}

startnetworks(){
  :>iirazzy.log
  for network in "${networks[@]}"; do
      source config.d/$network
      {
        while [[ -f $TMPFILE ]]; do
            echo "starting network $NETWORK"
            # cleanup
            echo "cleaning up $IRCDIR/$NETWORK/in"
            rm -f "$IRCDIR/$NETWORK/in"

            # connect to network 
            [[ ${#PASSWORD} != 0 ]] && PASSWORD="-k $PASSWORD"
            echo ii -i "$IRCDIR" -s "$NETWORK" -p "$PORT" -n "$NICK" -f "$FULLNAME" ${PASSWORD} 
            ii -i "$IRCDIR" -s "$NETWORK" -p "$PORT" -n "$NICK" -f "$FULLNAME" ${PASSWORD} &
            pid="$!"; echo "$pid " >> $TMPFILE;

            # wait for the connection
            while ! test -p "$IRCDIR/$NETWORK/in"; do echo "waiting for connection"; sleep 1; done

            # auth to services
            echo "authentication indentity"
            [[ -e "$IRCDIR/$NETWORK/ident" ]] && \
                printf -- "/j nickserv identify %s\n" "$(<"$IRCDIR/$NETWORK/ident")" > "$IRCDIR/$NETWORK/in"
            rm -f "$IRCDIR/$NETWORK/nickserv/out" # clean that up - ident passwd is in there

            # join channels
            for channel in ${CHANNELS[@]}; do
                echo "joining channel $channel"
                printf -- "/j %s\n" "$channel" > "$IRCDIR/$NETWORK/in"
                [[ -e "$IRCDIR/$NETWORK/$channel/out" ]] || touch "$IRCDIR/$NETWORK/$channel/out"
                monitor &
                pids+=($!)
            done          

            # if connection is lost reconnect
            wait "$pid"
            kill "${pids[@]}"
        done 2>&1 | while read line; do echo "[$(date) iirazzy] $line" >> iirazzy.log; done 
     } &
  done 
  # some privacy please, thanks
  chmod -R 770 "$IRCDIR"
  #chmod 600 "$IRCDIR"/*/ident &>/dev/null

}

stop(){
  ps aux | grep iirazzy | grep -v stop | tr -s " " | cut -d' ' -f 2 | while read pid; do kill -9 $pid &>/dev/null; done; 
  [[ -f $TMPFILE ]] && pid=$(cat $TMPFILE) && rm $TMPFILE 
  echo "killing $pid"
  kill -9 $pid &>/dev/null  || echo "could not stop iirazzy :("
  echo "iirazzy stopped"
}

"$@" 
